name: Deploy WordPress theme

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: deploy-wordpress-theme
  cancel-in-progress: true

jobs:
  deploy:
    name: Upload theme by FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy atnif-theme
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./wordpress/wp-content/themes/atnif-theme/
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          exclude: |
            **/.DS_Store
